version: '3.5'

services:
  postgres:
    container_name: postgres_container
    image: postgres:14
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-app}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
       - ./contrib/migrations:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

  app:
    depends_on:
      - postgres
    container_name: app
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      DATABASE_URL: "postgresql+asyncpg://postgres:changeme@postgres/app"
    ports:
      - "8000:8000"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
    postgres: